---
num_workers: 100
inventory: nornir.plugins.inventory.simple.SimpleInventory
SimpleInventory:
    host_file: "mrosi@MBP-di-Mario-2:~/Documents/GitHub/Python_LAB/Nornir_Python/hosts.yaml"
    group_file: "mrosi@MBP-di-Mario-2:~/Documents/GitHub/Python_LAB/Nornir_Python/groups.yaml"